seed: 42
data:
  path: data/bitcoin2015to2017_close.h5
  label_feature: 0
model:
  name: lstm
  units: 50
  output_size: 16
  dropout: 0.2
  l1_reg: 0.0
train:
  epochs: 50
  batch_size: 8
  output_name: bitcoin2015to2017_close_LSTM_1_tanh_leaky
